name: 'OSS Gate Issue Cleaner'
description: 'Cleaning issues of OSS Gate Workshop repository'
inputs:
  GITHUB_TOKEN:
    description: Secret GitHub API token to making API requests
    required: true
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
